### ISSUE TITLE
Chopping domain when editing remote files fails DNS resolution

### ISSUE THREAD

**Issue by xmacex** [p3r7/norns.el#1]
Moving from [llllllllines discussion](https://llllllll.co/t/norns-el-emacs-norns/52622/22?u=xmacex) to issue.

The `norns--core-curr-host` function chops the value of `norns-mdns-domain` from the hostname on line 248 whenever we are editing a remote file. I have not changed any settings of the mode.

https://github.com/p3r7/norns.el/blob/b82aa3dbaef1216edcf06fd6db66abb17cd91a4a/norns.el#L238-L249

<kbd>M-x</kbd> `norns-maiden-send` <kbd>RET</kbd> `print("hi")` <kbd>RET</kbd>

```
norns/5555 nodename nor service provided, or not known
```

However if I comment out that line 248 (and rebalance the parentheses)))), `norns-maiden-send` does what I expect.

<kbd>M-x</kbd> `norns-maiden-send` <kbd>RET</kbd> `print("hi")` <kbd>RET</kbd>

```lua
hi
<ok>

maiden>>
```

Also the REPL works just fine.

On my Android wifi hotspot I can get to norns.local just fine from browser, SSH or TRAMP, but there is no such host as `norns` without the domain. Same behavious whether I run Emacs on macOS or on Android in Termux, and open a file on norns over TRAMP.

I am missing the rationale for chopping the domain... What would work in my case, would be to remove the chopping ie the entire line 248, or make it conditional or customizeable if it serves some purpose when connecting without a domain. [The monome docs about connecting over network](https://monome.org/docs/norns/wifi-files/) as well as [advanced ways](https://monome.org/docs/norns/advanced-access/) use the full hostname+domain `norns.local`.

Thanks for this mode, it is great fun <3

**Comment by p3r7** [comment]
thanks again for reporting & investigating this.

i honestly don't remember exactly why i did this specifically but i guess it was either for a platform-specific (maybe Windows?) behavior or due to a specific network setup (`.local` is valid on my network but it's mDNS domain seems to be `.lan`).

to fix this:
 - if it was due to an OS-specific behavior, handle the different cases transparently for the user
 - if it's network specific, make it configurable, w/ the simpler use-case the default
 - if there was no reason whatsoever, let's just keep this suffix

i'll need to parse the commit logs & do some tests on my end.

**Comment by xmacex** [comment]
https://github.com/p3r7/norns.el/blame/96802382da9f36cf785fe32bd06d9dc3edfc5820/norns.el#L146 

https://github.com/p3r7/norns.el/commit/df8502ee03c613d4fc43f5b2e37de0906e18a789#diff-32c498dd694d6862c9c6ef163eaede18480145086ba8916c870f4802b636b98eR94-R97

**Comment by p3r7** [comment]
mhm, it's either a Windows specific thing or i messed up when adding support for [dockerized norns](https://github.com/schollz/norns-desktop).

**Comment by xmacex** [comment]
Sorry I have no experience on either. norns in Docker with Emacs is such an {ince,contra}ption I get vertigo simply thinking about it.

**Comment by ergodicbreak** [comment]
hello @p3r7, thanks for norns.el I got started with it tonight! I needed to rebind norns-mdns-domain from "local" to "lan" for the maiden-repl to work on my Manjaro Linux laptop (oddly I use norns.local in the browser) -- not sure if that's in the scope of this issue but it seemed related.

**Comment by p3r7** [comment]
> not sure if that's in the scope of this issue but it seemed related.

i'm not sure really.

> needed to rebind norns-mdns-domain from "local" to "lan"

the aim of those vars is to rebind them. they come with default values but are essentially config.

**Comment by julianrubisch** [comment]
almost a year later, I'm running into this as well. sad to find an emacs package for norns and then not being able to use it :-/

is there anything I can do to help fix this? maybe just a config flag?

**Comment by p3r7** [comment]
so thinking again about this, chopping off the norns-advertized suffix (`norns-mdns-domain`, typically `.local`) is volountary, as it wouldn't work w/ SSH/TRAMP when you have a network router in the middle w/ a different mDNS domain (typically `.lan`, configurable `norns-local-mdns-domain`) .

i guess we should whop this suffix but add back the `norns-local-mdns-domain`. if one does a direct connection to norns, they'd have to customize the `norns-local-mdns-domain` to `.local`.

i'll push a fix & update the readme.

**Comment by p3r7** [comment]
so after doing more test, it seems that both `.local` and `.lan` work with TRAMP on my linux box (w/ both SSH & websocket).

so either on an older Emacs version or when i was under Windows that Emacs/TRAMP didn't understood the `local` mDNS domain.

i guess i'll simplify the code to use & suffix w/ `.local` by default, unless a `norns-lan-domain` is specified.

**Comment by p3r7** [comment]
> i guess i'll simplify the code to use & suffix w/ `.local` by default, unless a `norns-lan-domain` is specified.

i did just that.

also, regarding.

> so after doing more test, it seems that both `.local` and `.lan` work with TRAMP on my linux box (w/ both SSH & websocket)

this is in fact kinda wrong. [`websocket`](https://github.com/emacsmirror/websocket) seem to sometimes fail to resolve `norns.local` on my setup (while `norns.lan` **always** work).

**Comment by xmacex** [comment]
FYI with this change, I needed to change the above mentioned `norns-lan-domain` from default `nil` to the empty string `""` while running Emacs directly on norns.

Setting `norns-mdns-domain` from default `"local"` to `nil` also seems to work I think.
